/**
 * Zod schemas of the Kandidator question pool files (ROADMAP S4).
 * questions.json and candidates.json are written by the maintainer;
 * scrutins.json and groups.json are generated by `pnpm kandidator:pool`.
 */
import { z } from "zod";

const SCRUTIN_URL = /^https:\/\/www\.assemblee-nationale\.fr\/dyn\/17\/scrutins\/\d+$/;

const groupRef = z.string().regex(/^PO\d+$/);
const count = z.number().int().nonnegative();

export const questionSchema = z.object({
  /** Stable, short: it is encoded in share URLs. */
  id: z.string().regex(/^[a-z0-9-]+$/),
  scrutinNumber: z.number().int().positive(),
  /** METHODOLOGY.md §7: +1, "Yes" agrees with a vote for the scrutin; -1, with a vote against it. */
  polarity: z.union([z.literal(1), z.literal(-1)]),
  /** Short French label, e.g. "Retraites". */
  topic: z.string().min(1),
  /** One short neutral French sentence (EDITORIAL_GUIDELINES.md §7). */
  text: z.string().min(1),
});

export const questionsSchema = z.array(questionSchema).min(1);

export const groupSchema = z.object({
  ref: groupRef,
  abbreviation: z.string().min(1),
  name: z.string().min(1),
});

export const groupsSchema = z.array(groupSchema).min(2);

/** Categories kept distinct (METHODOLOGY.md §4–5). */
export const groupBreakdownSchema = z.object({
  ref: groupRef,
  for: count,
  against: count,
  abstention: count,
  nonVoting: count,
  absent: count,
});

export const scrutinSchema = z.object({
  number: z.number().int().positive(),
  uid: z.string().min(1),
  date: z.iso.date(),
  /** Official title, as published. */
  title: z.string().min(1),
  sourceUrl: z.string().regex(SCRUTIN_URL),
  groups: z.array(groupBreakdownSchema).min(1),
});

export const scrutinsFileSchema = z.object({
  legislature: z.literal(17),
  sources: z
    .array(
      z.object({
        id: z.string().min(1),
        url: z.url(),
        retrievedAt: z.iso.datetime(),
        sha256: z.string().regex(/^[0-9a-f]{64}$/),
      }),
    )
    .min(1),
  scrutins: z.array(scrutinSchema).min(1),
});

/** METHODOLOGY.md §6 — explicit, sourced association between a declared candidate and a group. */
export const associationSchema = z.object({
  groupRef,
  type: z.enum(["group-member", "party-forming-group", "group-support"]),
  /** "party-forming-group" needs two: the person's party, and the party–group link. */
  sourceUrls: z.array(z.url()).min(1),
  /** Date the association was established or checked. */
  date: z.iso.date(),
});

export const candidateSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  name: z.string().min(1),
  declarationSourceUrl: z.url(),
  declarationDate: z.iso.date(),
  associations: z.array(associationSchema),
});

export const candidatesSchema = z.array(candidateSchema);

export type PoolQuestion = z.infer<typeof questionSchema>;
export type PoolGroup = z.infer<typeof groupSchema>;
export type PoolScrutin = z.infer<typeof scrutinSchema>;
export type ScrutinsFile = z.infer<typeof scrutinsFileSchema>;
export type Candidate = z.infer<typeof candidateSchema>;
