import { MIN_EXPRESSED } from "../../src/domain/kandidator/parameters.ts";
import type { Group } from "./normalize.ts";
import type { RankingOptions, ScrutinAnalysis } from "./rank.ts";
import type { Retrieval } from "./schemas.ts";

export type ShortlistInput = {
  retrieval: Retrieval;
  options: RankingOptions;
  scrutinsRead: number;
  eligible: number;
  excluded: { number: number; reason: string }[];
  groups: Group[];
  shortlist: ScrutinAnalysis[];
};

/** Rounding for readability only; ranking uses exact values. */
const round = (value: number): number => {
  return Math.round(value * 1000) / 1000;
};

/** Committed JSON. No generation timestamp, so re-running on the same cache gives the same file. */
export const toJson = (input: ShortlistInput) => {
  return {
    legislature: input.retrieval.legislature,
    sources: input.retrieval.sources,
    parameters: {
      MIN_EXPRESSED,
      minKnownGroupsRatio: round(input.options.minKnownGroupsRatio),
      size: input.options.size,
      required: input.options.required,
      excludedFromRanking: input.options.excludedGroupRefs,
    },
    stats: { scrutinsRead: input.scrutinsRead, excluded: input.excluded.length, eligible: input.eligible },
    excludedScrutins: input.excluded,
    groups: input.groups,
    shortlist: input.shortlist.map((analysis, index) => ({
      rank: index + 1,
      number: analysis.scrutin.number,
      uid: analysis.scrutin.uid,
      date: analysis.scrutin.date,
      title: analysis.scrutin.title,
      voteType: analysis.scrutin.voteType,
      result: analysis.scrutin.result,
      sourceUrl: analysis.scrutin.sourceUrl,
      score: round(analysis.score),
      discrimination: round(analysis.discrimination),
      cohesion: round(analysis.cohesion),
      participation: round(analysis.participation),
      pattern: analysis.pattern,
      groups: analysis.scrutin.groups.map((group) => {
        const position = analysis.positions.get(group.groupRef);

        return {
          ref: group.groupRef,
          members: group.members,
          ...group.breakdown,
          reportedVoluntaryNonVoting: group.reportedVoluntaryNonVoting,
          majorityPosition: group.majorityPosition,
          // null: unknown (too few expressed votes) or not ranked (non-inscrits).
          position: position?.kind === "known" ? round(position.value) : null,
        };
      }),
    })),
  };
};

const escapeCell = (text: string): string => {
  return text.replaceAll("|", "\\|").replaceAll("\n", " ");
};

const formatPosition = (value: number | null): string => {
  if (value === null) return "?";

  return `${value > 0 ? "+" : ""}${value.toFixed(2)}`;
};

/** Human-readable table for the maintainer's selection (D3). */
export const toMarkdown = (input: ShortlistInput): string => {
  const json = toJson(input);
  const abbreviation = new Map(input.groups.map((group) => [group.ref, group.abbreviation]));
  const lines = [
    `# Kandidator scrutin shortlist — legislature ${json.legislature}`,
    "",
    "Generated by `pnpm kandidator:shortlist` (see `docs/METHODOLOGY.md` §11). Do not edit by hand.",
    "",
    ...json.sources.map((source) => `- Source \`${source.id}\`: ${source.url} (retrieved ${source.retrievedAt})`),
    `- Scrutins read: ${json.stats.scrutinsRead}, excluded for data issues: ${json.stats.excluded}, eligible: ${json.stats.eligible}, kept: ${json.shortlist.length} (ranked: ${json.parameters.size}, required: ${json.parameters.required.join(", ") || "none"})`,
    "- Position per group: (for − against) / (for + against + abstention), `?` = unknown or not ranked.",
    "",
    "| # | Scrutin | Date | Type | Result | Score | Discr. | Cohesion | Particip. | Positions | Title |",
    "|---|---|---|---|---|---|---|---|---|---|---|",
    ...json.shortlist.map((entry) => {
      const positions = entry.groups
        .map((group) => `${abbreviation.get(group.ref) ?? group.ref} ${formatPosition(group.position)}`)
        .join(", ");

      return `| ${entry.rank} | [${entry.number}](${entry.sourceUrl}) | ${entry.date} | ${entry.voteType.code} | ${entry.result} | ${entry.score} | ${entry.discrimination} | ${entry.cohesion} | ${entry.participation} | ${positions} | ${escapeCell(entry.title)} |`;
    }),
    "",
  ];
  if (json.excludedScrutins.length > 0) {
    lines.push("## Excluded scrutins (upstream data issues)", "");
    lines.push(...json.excludedScrutins.map((e) => `- [${e.number}](https://www.assemblee-nationale.fr/dyn/${json.legislature}/scrutins/${e.number}): ${e.reason}`));
    lines.push("");
  }

  return lines.join("\n");
};
